// Generated by Wrangler by running `wrangler types`

interface Env {
	PING_API_KEY: "";
	AI_MODEL_API_URL: "https://integrate.api.nvidia.com";
	AI_MODEL_NAME: "nvidia/llama-3.1-nemotron-nano-vl-8b-v1";
	DB: D1Database;
}
